name: hetu_otp_util
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hetu_script: ^0.4.2+1
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
